add sign in logic
duniapay/mobileApp pull request #18
Opened 2020-12-24 15:25 UTC by PogudoTanya

2020-12-28 17:23 UTC, apsevkin requested changes

2020-12-28 17:23 UTC, apsevkin commented on src/resources/user/user.reducer.js
> +        accessToken: action.userData.accessToken,
let's set authenticated here to avoid 2 actions dispatch

2020-12-28 17:23 UTC, apsevkin commented on src/screens/SignIn/SignIn.jsx
> +        await dispatch(userActions.signIn(values));
it would be better to avoid 2 dispatch calls

2020-12-28 17:23 UTC, apsevkin commented on src/screens/SignIn/SignIn.jsx
> +            setFieldError('password', e.data.credentials);
let's add error only for one field, or add another error message after form fields

2020-12-29 08:18 UTC, liubaterehova commented on src/screens/SignIn/SignIn.jsx
> +          if (e.data.credentials) {
add e?.data.credentials

2020-12-29 13:06 UTC, liubaterehova approved these changes

2020-12-29 13:10 UTC, liubaterehova approved these changes

2020-12-29 13:10 UTC, merged