add headerHomepage
duniapay/mobileApp pull request #25
Opened 2021-01-06 11:42 UTC by PogudoTanya

2021-01-13 10:27 UTC, apsevkin commented
<img width="345" alt="Screen Shot 2021-01-13 at 13 26 16" src="https://user-images.githubusercontent.com/46781149/104440197-1aa54100-55a3-11eb-9422-65b50aeac8bd.png">
add padding

2021-01-13 10:28 UTC, apsevkin commented
<img width="353" alt="Screen Shot 2021-01-13 at 13 25 36" src="https://user-images.githubusercontent.com/46781149/104440235-27299980-55a3-11eb-884a-28b5bf9cdd7e.png">
change status bar background color

2021-01-13 11:34 UTC, apsevkin commented
![Uploading Screen Shot 2021-01-13 at 14.34.22.png…]()

2021-01-13 11:35 UTC, apsevkin commented
<img width="910" alt="Screen Shot 2021-01-13 at 14 34 22" src="https://user-images.githubusercontent.com/46781149/104447198-8344eb80-55ac-11eb-80fa-104034e5d3b2.png">

2021-01-19 15:19 UTC, liubaterehova commented on package.json
> +    "react-native-parallax-header": "1.1.4",
u don't use it

2021-01-19 15:24 UTC, liubaterehova requested changes

2021-01-19 15:24 UTC, liubaterehova commented on package.json
> +    "react-native-sticky-parallax-header": "0.4.0",
u don't use it

2021-01-20 15:26 UTC, closed without merging