Feat: create 2 screens: deposit with card and phone»
duniapay/mobileApp pull request #30
Opened 2021-01-15 14:36 UTC by liubaterehova

2021-01-15 16:39 UTC, apsevkin requested changes

2021-01-15 16:39 UTC, apsevkin commented on src/components/ConfirmDeposit/ConfirmDeposit.jsx
> +    if (inputRef.current) inputRef.current.focus();
use autoFocus props for TextInput instead useEffect

2021-01-15 16:39 UTC, apsevkin commented on src/components/ConfirmDeposit/ConfirmDeposit.jsx
> +      if (processedMoney) {
setDisabled(!processMoney);

2021-01-15 16:39 UTC, apsevkin commented on src/screens/ConfirmMobileDeposit/ConfirmMobileDeposit.jsx
> +  // const { phoneOperator, phoneNumber } = route.params;
.

2021-01-15 16:39 UTC, apsevkin commented on src/screens/ConfirmCardDeposit/ConfirmCardDeposit.jsx
> +  // const { cardPayment, cardName, cardExpirationDate, cardNumber } = route.params;
.

2021-01-15 17:52 UTC, liubaterehova commented on src/components/ConfirmDeposit/ConfirmDeposit.jsx
> +    if (inputRef.current) inputRef.current.focus();
I used it. But in ios platform it adds to keyboard padding and we can avoid it only if I make like this.

2021-01-16 15:01 UTC, apsevkin approved these changes

2021-01-16 15:01 UTC, merged