feat: add screen ResetPassword
duniapay/mobileApp pull request #4
Opened 2020-12-11 18:31 UTC by liubaterehova

2020-12-15 09:52 UTC, arlovaalina requested changes

2020-12-15 09:52 UTC, arlovaalina commented on src/components/HeaderAuthLayout/HeaderAuthLayout.styles.js
> +import { getStatusBarHeight } from 'react-native-status-bar-height';
Why do you use that? It is useless, we have SafeAreaView component, which avoids status bar.

2020-12-15 09:52 UTC, arlovaalina commented on src/screens/ResetPassword/ResetPassword.jsx
> +              {'\n'}
It's better to use just two Text components instead of using break line.

2020-12-15 09:52 UTC, arlovaalina commented on src/screens/ResetPassword/ResetPassword.jsx
> +    const isValid = str.length > 8 && str === repeatPassword && !validate(str, 'password');
Let's move it to constant.

2020-12-15 09:52 UTC, arlovaalina commented on src/components/HeaderAuthLayout/HeaderAuthLayout.styles.js
> +import { getStatusBarHeight } from 'react-native-status-bar-height';
Let's create wrapper for each screen with SafeAreaView and StatusBar, this should solve the problem.

2020-12-16 11:39 UTC, apsevkin approved these changes

2020-12-16 11:40 UTC, merged