contacts cross
duniapay/mobileApp pull request #65
Opened 2021-02-22 12:13 UTC by PogudoTanya

2021-02-25 10:01 UTC, liubaterehova requested changes

2021-02-25 10:01 UTC, liubaterehova commented on src/screens/ChooseContact/components/ContactServerList/ContactServerList.jsx
> +          key={Math.random()}
key={recepientId}

2021-02-26 09:26 UTC, apsevkin requested changes

2021-02-26 09:26 UTC, apsevkin commented on src/screens/ChooseContact/ChooseContact.jsx
> +    .filter(({ phoneNumbers }) => {
let's use arrow functions without body

2021-02-26 09:26 UTC, apsevkin commented on src/screens/ChooseContact/ChooseContact.jsx
>      if (Platform.OS === 'android') {
use async function

2021-02-26 09:26 UTC, apsevkin commented on src/screens/ChooseContact/ChooseContact.jsx
>    const [listPhoneContacts, setListPhoneContacts] = useState([]);
get rid of this state

2021-02-26 10:42 UTC, apsevkin approved these changes

2021-02-26 11:05 UTC, liubaterehova approved these changes

2021-02-26 11:06 UTC, merged