[DYN-39]feat: make homepage for crypta currencies
duniapay/mobileApp pull request #66
Opened 2021-02-25 08:29 UTC by liubaterehova

2021-03-01 14:32 UTC, apsevkin requested changes

2021-03-01 14:32 UTC, apsevkin commented on src/screens/More/More.jsx
> +        onCardClick={() => {
move it out from JSX

2021-03-01 14:32 UTC, apsevkin commented
Back arrow on the crypto homepage doesn't work

2021-03-01 14:34 UTC, apsevkin commented
When we click more button second time the list with options doesn't show
<img width="277" alt="Screen Shot 2021-03-01 at 17 34 21" src="https://user-images.githubusercontent.com/46781149/109511695-5c873980-7ab4-11eb-9216-1884305d7861.png">

2021-03-02 09:31 UTC, arlovaalina requested changes

2021-03-02 09:31 UTC, arlovaalina commented on src/components/HomepageHeader/components/leftIcon/LeftIcon.jsx
> +const AvatarIcon = ({ avatarUrl, username }) => {
I think it is better to move AvatarIcon component into separate file

2021-03-02 09:31 UTC, arlovaalina commented on src/screens/CryptoHomepage/CryptoHomepage.jsx
> +      return { crypto: '₿', text: 'Bitcoin total balance' };
Maybe let's move these currency signs into file with constants. I saw you use them in many other places.

2021-03-04 12:20 UTC, closed without merging