[DYN-41]feat: add sell/buy crypto and congratulations
duniapay/mobileApp pull request #72
Opened 2021-02-26 14:47 UTC by liubaterehova

2021-03-01 21:34 UTC, arlovaalina requested changes

2021-03-01 21:34 UTC, arlovaalina commented on src/components/DailyTransactions/DailyTransactions.jsx
>    }, [date, transactions.length]);
Do we really need `transactions.length` in dependencies?

2021-03-01 21:34 UTC, arlovaalina commented on src/helpers/constants.js
> +export const KEYBOARD_VERTICAL_OFFSET = () => {
Does it work? Now it is a function, but you use it as a simple value. Previously it was wrapped in `useMemo`, that's why we could use it as a value.

2021-03-01 21:34 UTC, arlovaalina commented on src/screens/CryptoOperations/components/ConvertCard/ConvertCard.jsx
> +  let convertFrom = (
Hmm, it is not a good practice to assign jsx to variable in such way. If you do that, you should think about creating a new component.

2021-03-01 21:36 UTC, arlovaalina requested changes

2021-03-01 21:36 UTC, arlovaalina commented on src/components/ConfirmDeposit/ConfirmDeposit.jsx
> +          keyboardVerticalOffset={KEYBOARD_VERTICAL_OFFSET}
Here you use constant as a value, but actually it is a function. I think you should choose: either leave it as a function (but then it is better to remove it from constants and give it another name starting with a verb) or make from it a value.

2021-03-02 09:01 UTC, apsevkin requested changes

2021-03-04 13:27 UTC, arlovaalina requested changes

2021-03-04 13:27 UTC, arlovaalina commented on src/screens/CryptoOperations/components/ConvertCards/ConvertCards.jsx
> +          setCards((state) => ({ from: state.to, to: state.from }))
And this

2021-03-04 13:27 UTC, arlovaalina commented on src/screens/CryptoOperations/components/ConvertCards/ConvertCards.jsx
> +        setValue={(e) => handleChangeMoney(e, cards.to.currency)}
And this

2021-03-04 13:27 UTC, arlovaalina commented on src/screens/CryptoOperations/components/ConvertCards/ConvertCards.jsx
> +        setValue={(e) => handleChangeMoney(e, cards.from.currency)}
Let's move it into separate function.

2021-03-04 13:27 UTC, arlovaalina commented on src/screens/CryptoOperations/components/ConvertCards/ConvertCards.jsx
> +function ConvertCard({ cards, setCards, handleChangeMoney }) {
Why do you have two components in one file?

2021-03-04 13:27 UTC, arlovaalina commented on src/screens/CryptoOperations/CryptoOperations.jsx
> +  const cardsValues = {
Let's wrap it into `useMemo`, otherwise each render will create a new object.

2021-03-04 14:24 UTC, arlovaalina approved these changes

2021-03-04 14:29 UTC, merged